#!/bin/bash

set -euo pipefail
. /.functions

require_dir_readable "${SSL_DIR}"
require_file_readable "${SSL_DIR}/.env"

#
# Init all the SSL-related stuff
#
init_ssl

CMD=(
	keytool -list
		-keystore "${JAVA_KEYSTORE}"
		-storetype "${JAVA_KEYSTORE_TYPE}"
		-storepass "$(<"${JAVA_KEYSTORE_PASSWORD_FILE}")"
		${JAVA_KEYTOOL_PROVIDER_FLAGS}
)
exec "${CMD[@]}"
