#!/bin/bash

set -euo pipefail
. /.functions

require_dir_readable "${SSL_DIR}"
require_file_readable "${SSL_DIR}/.env"

#
# Init all the SSL-related stuff
#
wait_ssl

CMD=(
	keytool -list
		-keystore "${JAVA_KEYSTORE}"
		-storetype "${JAVA_KEYSTORE_TYPE}"
		-storepass "$(<"${JAVA_KEYSTORE_PASSWORD_FILE}")"
		${JAVA_KEYTOOL_PROVIDER_FLAGS}
)

eyes "Validating the ${JAVA_KEYSTORE_TYPE} keystore at [${JAVA_KEYSTORE}]..."
OUT="$( "${CMD[@]}" 2>&1 )" || fail "Failed to validate the keystore (rc=${?}):\n${OUT}"
ok "The keystore is valid!"
