#!/bin/bash

set -euo pipefail
. /.functions

require_dir_readable "${SSL_DIR}"
require_file_readable "${SSL_DIR}/.env"

#
# Init all the SSL-related stuff
#
init_ssl

CMD=(
	keytool -list
		-keystore "${JAVA_KEYSTORE}"
		-storetype "${JAVA_KEYSTORE_TYPE}"
		-storepass "$(<"${JAVA_KEYSTORE_PASSWORD_FILE}")"
)

if [ -n "${JAVA_KEYSTORE_PROVIDER}" ] ; then
	CMD+=( -providerclass "${JAVA_KEYSTORE_PROVIDER}" )
	[ -n "${JAVA_KEYSTORE_PROVIDER_PATH}" ] && CMD+=( -providerpath "${JAVA_KEYSTORE_PROVIDER_PATH}" )
fi

exec "${CMD[@]}"
