#!/bin/bash

. /.functions

#
# Set the minimum expected return values
#
export ZOOKEEPER_SSL="false"
export ZOOKEEPER_SSL_CLIENT_OPTIONS=""

#
# If the SSL stuff is enabled, we use it!
#
init_ssl || return 0

#
# All the SSL stuff is ready!
#
export ZOOKEEPER_SSL="true"

is_fips && ZOOKEEPER_HOSTNAME_VERIFICATION="false" || ZOOKEEPER_HOSTNAME_VERIFICATION="true"
export ZOOKEEPER_HOSTNAME_VERIFICATION

export ZOOKEEPER_PROTOCOL="TLSv1.3"
export ZOOKEEPER_ENABLED_PROTOCOLS="${ZOOKEEPER_PROTOCOL}"
export ZOOKEEPER_CIPHERS="TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256"

ZOOKEEPER_SSL_COMMON_OPTS=(
	-Dzookeeper.ssl.hostnameVerification="${ZOOKEEPER_HOSTNAME_VERIFICATION}"
	-Dzookeeper.ssl.protocol="${ZOOKEEPER_PROTOCOL}"
	-Dzookeeper.ssl.enabledProtocols="${ZOOKEEPER_ENABLED_PROTOCOLS}"
	-Dzookeeper.ssl.ciphersuites="${ZOOKEEPER_CIPHERS}"

	-Dzookeeper.ssl.keyStore.location="${JAVA_KEYSTORE}"
	-Dzookeeper.ssl.keyStore.passwordPath="${JAVA_KEYSTORE_PASSWORD_FILE}"
	-Dzookeeper.ssl.keyStore.type="${JAVA_KEYSTORE_TYPE}"

	-Dzookeeper.ssl.trustStore.location="${JAVA_TRUSTSTORE}"
	-Dzookeeper.ssl.trustStore.passwordPath="${JAVA_TRUSTSTORE_PASSWORD_FILE}"
	-Dzookeeper.ssl.trustStore.type="${JAVA_TRUSTSTORE_TYPE}"
)
export ZOOKEEPER_SSL_COMMON_OPTIONS="${ZOOKEEPER_SSL_COMMON_OPTS[@]}"
unset ZOOKEEPER_SSL_COMMON_OPTS

ZOOKEEPER_SSL_CLIENT_OPTS=(
	-Dzookeeper.clientCnxnSocket="org.apache.zookeeper.ClientCnxnSocketNetty"
	-Dzookeeper.client.secure="true"
	-Dzookeeper.sasl.client="false"
)
export ZOOKEEPER_SSL_CLIENT_OPTIONS="${ZOOKEEPER_SSL_CLIENT_OPTS[@]} ${ZOOKEEPER_SSL_COMMON_OPTIONS}"
unset ZOOKEEPER_SSL_CLIENT_OPTS

#
# Done!
#
